import os
import pickle
from contextlib import nullcontext
import torch
from k_model import ModelConfig, Transformer
from transformers import AutoTokenizer, AutoModelForCausalLM
import argparse

class TextGenerator:
    def __init__(self, 
                 checkpoint='./base_model_215M/pretrain_1024_18_6144.pth',  # Model checkpoint path
                 tokenizer_model_path='./tokenizer_k/',  # Word parterator model path
                 seed=42,  # Random seeds to ensure repeatability
                 device=None,  # Devices, use CUDA first, and use CPU if there is no available CUDA
                 dtype="bfloat16"):  # Data type, default is float32, you can choose float16 or bfloat16
        """Initialize the TextGenerator class, load the model, set the device and word segmentation, etc."""
        # Model loading configuration
        self.checkpoint = checkpoint  # Saved model checkpoint path
        self.tokenizer_model_path = tokenizer_model_path  # Word parter model file path
        self.seed = seed  # Random number seeds for the reproducibility of generation
        self.device = device or ('cuda:0' if torch.cuda.is_available() else 'cpu')  # Select equipment according to hardware conditions
        self.dtype = dtype  # Float number type of model
        self.device_type = 'cuda' if 'cuda' in self.device else 'cpu'  # Determine whether the current device is CUDA
        
        # Set random seeds to ensure the reproducibility of the generated
        torch.manual_seed(seed)  # Setting up CPU Random Seed
        torch.cuda.manual_seed(seed)  # Setting up CUDA random seeds
        torch.backends.cuda.matmul.allow_tf32 = True  # Allows CUDA to use TF32 precision for matrix multiplication
        torch.backends.cudnn.allow_tf32 = True  # Allow cuDNN to use TF32 precision acceleration
        
        # Select the appropriate automatic mixing accuracy context according to dtype
        ptdtype = {'float32': torch.float32, 'bfloat16': torch.bfloat16, 'float16': torch.float16}[self.dtype]
        self.ctx = nullcontext() if self.device_type == 'cpu' else torch.amp.autocast(device_type=self.device_type, dtype=ptdtype)
        
        # Loading the model checkpoint file
        checkpoint_dict = torch.load(self.checkpoint, map_location=self.device)  # Loading model parameters # Initialize model parameters
        self.model = Transformer(ModelConfig(dim=1024, n_layers=18))  # Instantiate the Transformer model
        sunwanted_prefix = '_orig_mod.'
        for k, v in list(checkpoint_dict.items()):
            if k.startswith(sunwanted_prefix):
                checkpoint_dict[k[len(sunwanted_prefix):]] = checkpoint_dict.pop(k)
        self.model.load_state_dict(checkpoint_dict, strict=False)
        
        # Calculate the model parameter quantity
        num_params = sum(p.numel() for p in self.model.parameters() if p.requires_grad)
        print(f"Model has {num_params / 1e6:.3f} M parameters.")
        # Set the model to evaluation mode to prevent operations such as dropout in training mode from affecting the results
        self.model.eval()
        # Place the model on the correct device (GPU or CPU)
        self.model.to(self.device)
        # Initialize word participle
        self.tokenizer = AutoTokenizer.from_pretrained(self.tokenizer_model_path)  # Load word segmenter according to specified path

    def chat_template(self, prompt):
        message = [
            {"role": "system", "content": "You are an AI assistant, your name is Xiao Ming."},
            {"role": "user", "content": prompt}
        ]
        return self.tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True)

    def sft_sample(self, 
               start="Hello!",  # The starting prompt word for generating text, which can be any string
               num_samples=3,  # The number of samples generated, 3 samples are generated by default
               max_new_tokens=256,  # The maximum number of tokens generated by each sample, a maximum of 256 tokens are generated by default.
               temperature=0.7,  # Control the randomness generated, 1.0 is the standard, the larger the value, the more random it is.
               top_k=300):  # The top_k tokens with the highest probability are retained, limiting the selection range during generation
        """Generate samples based on the given starting text.
        
        :param start: Generate text start word
        :param num_samples: Number of text samples to be generated
        :param max_new_tokens: The maximum number of tokens generated per sample
        :param temperature: Controls the randomness of generation. The smaller the value, the more certain it is generated. The larger the value, the more random it is generated.
        :param top_k: Limits the range of tokens selected during generation
        :return: Generated text sample list"""
        start = self.chat_template(start)
        # Encode the starting text into a token id sequence
        start_ids = self.tokenizer(start).data['input_ids']
        # print('start_ids:', start_ids)
        x = (torch.tensor(start_ids, dtype=torch.long, device=self.device)[None, ...])  # Convert the encoded token id to PyTorch tensor
        generated_texts = []  # Used to save generated text samples
        with torch.no_grad():  # Disable gradient calculation to improve efficiency
            with self.ctx:  # Enter the context of automatic mixing precision (if it is a GPU and float16 is used)
                for k in range(num_samples):  # Loop to generate a specified number of samples
                    y = self.model.generate(x, self.tokenizer.eos_token_id, max_new_tokens, temperature=temperature, top_k=top_k)  # Generate text
                    generated_texts.append(self.tokenizer.decode(y[0].tolist()))  # The decoded token sequence is readable text
        return generated_texts  # Returns the generated text sample


    def pretrain_sample(self, 
               start="Hello!",  # The starting prompt word for generating text, which can be any string
               num_samples=3,  # The number of samples generated, 3 samples are generated by default
               max_new_tokens=256,  # The maximum number of tokens generated by each sample, a maximum of 256 tokens are generated by default.
               temperature=0.7,  # Control the randomness generated, 1.0 is the standard, the larger the value, the more random it is.
               top_k=300):  # The top_k tokens with the highest probability are retained, limiting the selection range during generation
        """Generate samples based on the given starting text.
        
        :param start: Generate text start word
        :param num_samples: Number of text samples to be generated
        :param max_new_tokens: The maximum number of tokens generated per sample
        :param temperature: Controls the randomness of generation. The smaller the value, the more certain it is generated. The larger the value, the more random it is generated.
        :param top_k: Limits the range of tokens selected during generation
        :return: Generated text sample list"""
        # If start starts with 'FILE:', it means that the starting text is read from the file
        if start.startswith('FILE:'):
            with open(start[5:], 'r', encoding='utf-8') as f:
                start = f.read()  # Read file content as the starting text
        
        # Encode the starting text into a token id sequence
        start_ids = self.tokenizer(start).data['input_ids']
        # print('start_ids:', start_ids)
        x = (torch.tensor(start_ids, dtype=torch.long, device=self.device)[None, ...])  # Convert the encoded token id to PyTorch tensor
        # print(x.shape)
        generated_texts = []  # Used to save generated text samples
        with torch.no_grad():  # Disable gradient calculation to improve efficiency
            with self.ctx:  # Enter the context of automatic mixing precision (if it is a GPU and float16 is used)
                for k in range(num_samples):  # Loop to generate a specified number of samples
                    y = self.model.generate(x, max_new_tokens=max_new_tokens, temperature=temperature, top_k=top_k)  # Generate text
                    generated_texts.append(self.tokenizer.decode(y[0].tolist()))  # The decoded token sequence is readable text
        
        return generated_texts  # Returns the generated text sample
    
if __name__ == "__main__":
    print("------------------- Pretrain Sample ------------------- \n")

    pretrain_prompt_datas = [
        '<|im_start|> Peking University is',
        '<|im_start|> School of Earth Science and Surveying Engineering, China University of Mining and Technology (Beijing)',
    ]

    generator = TextGenerator(checkpoint='./base_model_215M/pretrain_1024_18_6144.pth')  # Initialize the generator
    for i in range(len(pretrain_prompt_datas)):
        samples = generator.pretrain_sample(start=pretrain_prompt_datas[i], num_samples=1, max_new_tokens=120, temperature=0.75)
        print(f"\nSample {i+1}:\n{pretrain_prompt_datas[i]}{samples[0]}\n{'-'*20}")  # Print the generated samples and divide them with dividers

    print("\n ------------------- SFT Sample ------------------- \n")

    sft_prompt_datas = [
        'hello',
        "Where is the capital of China?",
        "What does 1+12 equal?",
        "Who are you?"
    ]
    generator = TextGenerator(checkpoint='./sft_model_215M/sft_dim1024_layers18_vocab_size6144.pth')  # Initialize the generator
    for i in range(len(sft_prompt_datas)):
        samples = generator.sft_sample(start=sft_prompt_datas[i], num_samples=1, max_new_tokens=128, temperature=0.6)
        print(f"\nSample {i+1}:\nQuestion: {sft_prompt_datas[i]} \nAI answer: {samples[0]}\n{'-'*20}")  # Print the generated samples and divide them with dividers

    
